import "./scripts/global";
import "./scripts/animations";
import "./scripts/header";
import "./scripts/cookie_notice";
import "./scripts/search-auto-complete";
import "./scripts/promo-banner";
import "./scripts/sliders.js";
import "./blocks-assets/scripts/_block-assets.js";
import "./scripts/shop-page.js";